name: stx_easy_localization_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0

homepage: https://github.com/VolodymyrSydorko/stx_easy_localization_generator
repository: https://github.com/VolodymyrSydorko/stx_easy_localization_generator
documentation: https://github.com/VolodymyrSydorko/stx_easy_localization_generator

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.2
  args: ^2.3.1


dev_dependencies:
  lints: ^2.0.0
